algorithm = "groth16"
voting_logic = "quadratic cost & 1v1c"

state_tree_depth = "2"
int_state_tree_depth = "1"
vote_options_tree_depth = "1"
batch_size = "5"

ptau = "powersOfTau28_hez_final_22.ptau"

[zkeys_tar_sha256]
hash = "83cdc02abfc33c2d99f4f32d8d32b885e8d5ad383bbadf88dd25ba159a6e6391"

[[contribution]]
name = "Dorahacks"
source = "official"
