algorithm = "groth16"
voting_logic = "quadratic cost & 1p1v"

state_tree_depth = "9"
int_state_tree_depth = "4"
vote_options_tree_depth = "3"
batch_size = "625"

ptau = "powersOfTau28_hez_final_24.ptau"

# [zkeys_tar_sha256]
# hash = ""

[[contribution]]
name = "Dorahacks"
source = "official"
