algorithm = "groth16"
voting_logic = "quadratic cost"

state_tree_depth = "7"
int_state_tree_depth = "3"
vote_options_tree_depth = "3"
batch_size = "125"

ptau = "powersOfTau28_hez_final_22.ptau"

[zkey_sha256]
msg = "dc25254b7565b2dddc9c182cbe76429bcc5ac0e7d102d515b0f46d5e0d85e1f9"
tally = "c842a186c95d00c37947e6e66cf71f27d3942acfb6fd57b8cec9ee57040edf41"

[[contribution]]
name = "Dorahacks"
source = "official"
